sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo umount /usr/src /usr/obj'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo mount smash.woods.am:/usr/src /usr/src && sudo mount smash.woods.am:/usr/obj /usr/obj'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo beadm create $BENAME && sudo beadm mount $BENAME /tmp/newbe && sudo beadm list' env='{BENAME: rXXXXXX}'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo pkg -c /tmp/newbe upgrade -r FreeBSD-base -Fy'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo pkg -c /tmp/newbe upgrade -r FreeBSD-base -n'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo pkg -c /tmp/newbe upgrade -r FreeBSD-base -y'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'diff <(sudo pkg -c /tmp/newbe rquery -r FreeBSD-base %n) <(sudo pkg -c /tmp/newbe query -e "%o = base" %n) | grep -v lib32 | grep "^[<>]"' shell='/usr/local/bin/zsh'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo pkg -c /tmp/newbe install -r FreeBSD-base -y XXX'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo etcupdate -D /tmp/newbe && sudo make -C /usr/src -DBATCH_DELETE_OLD_FILES delete-old DESTDIR=/tmp/newbe'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo make -C /usr/src -DBATCH_DELETE_OLD_FILES delete-old-libs DESTDIR=/tmp/newbe'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo umount /usr/src /usr/obj'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am,smash.woods.am' cmd.run 'sudo pkg -c /tmp/newbe clean -ay'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am,smash.woods.am' cmd.run 'sudo pkg -c /tmp/newbe upgrade -r FreeBSD-ports -Fy'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am,smash.woods.am' cmd.run 'sudo pkg -c /tmp/newbe upgrade -r FreeBSD-ports -n'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am,smash.woods.am' cmd.run 'sudo pkg -c /tmp/newbe upgrade -r FreeBSD-ports -y'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am,smash.woods.am' cmd.run 'sudo pkg -c /tmp/newbe autoremove -y' 
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am,smash.woods.am' cmd.run 'sudo pkg -c /tmp/newbe upgrade -r FreeBSD-ports -fFy'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am,smash.woods.am' cmd.run 'sudo pkg -c /tmp/newbe upgrade -r FreeBSD-ports -fn'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am,smash.woods.am' cmd.run 'sudo pkg -c /tmp/newbe upgrade -r FreeBSD-ports -fy'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am,smash.woods.am' cmd.run 'sudo pkg -c /tmp/newbe clean -ay'
sudo salt -C 'L@freenas.woods.am,sparticus.woods.am,shinto.woods.am,slappy.woods.am' cmd.run 'sudo beadm umount $BENAME && sudo beadm activate $BENAME && sudo beadm list' env='{BENAME: rXXXXXX}'
sudo salt -C 'L@sparticus.woods.am' cmd.run 'shutdown -r now'
sudo salt -C 'L@shinto.woods.am,slappy.woods.am' cmd.run 'shutdown -r now'
sudo salt -C 'L@freenas.woods.am' cmd.run 'shutdown -r now'
